### ISSUE TITLE
Violations from ReviewAsset function do not contain constraint configs

### ISSUE THREAD

**Issue by katze120** [forseti-security/config-validator#120]
Originally, [cft scorecard](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/cli/docs/scorecard.md) uses [Audit](https://github.com/forseti-security/config-validator/blob/master/pkg/gcv/cf/cf.go#L247) function which includes constraint metadata as part of violations. Scorecard uses some annotations in the constraint metadata to categorize the violations.

With the [recent update](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/commit/5ec74956a21b4d12e4c121442cac47e8feda528c#diff-c2e938ad50da5c60fd69ffc42437518fR33) to use [ReviewAsset](https://github.com/forseti-security/config-validator/blob/master/pkg/gcv/validator.go#L157) function, the violations no longer contain constraint config.

@briantkennedy is this something you can help here?

**Comment by briantkennedy** [comment]
I'll take a look, is constraint name sufficient or do we everything (match block target/exclude, parameters)?

**Comment by morgante** [comment]
Everything is what we had, but the main thing we need is actually the annotations (from the constraint metadata).

**Comment by briantkennedy** [comment]
Sounds good, which metadata key would you like the annotations map to exist at?

**Comment by katze120** [comment]
Scorecard has been using the `bundles.validator.forsetisecurity.org/scorecard-v1` key, for example: https://github.com/forseti-security/policy-library/blob/master/samples/iam_blacklist_public.yaml#L7

But is it possible to provide all metadata keys & values like the previous behaviour? In case we need to leverage additional metadata fields in future.
We were not getting info such as match block target/exclude and parameters, only the constraint metadata.
Previous implementation code here: https://github.com/forseti-security/config-validator/blob/master/pkg/gcv/cf/parsing.go#L91

**Comment by morgante** [comment]
If for some reason returning the full metadata isn't possible, returning `Metadata.Annotations` should be sufficient.

**Comment by katze120** [comment]
hi @briantkennedy , any idea when this can be resolved?

scorecard uses constraint metadata to generate constraint category, which is good to have and previously available feature, but from my understand it's not widely use yet. So depending on the timeline, we need to see whether new version of cft cli can/should be released.. I'd love to use the new features in new cft cli to generate resource ancestry path, for downstream integration.  @morgante any thoughts?

**Comment by katze120** [comment]
Thanks for looking into this! I've started testing the new version with cft scorecard.
Verified that constraint metadata is there. 
Also found that the constraint name now also contains the template name, e.g. `iam-gcs-blacklist-public-users` becomes `GCPStorageBucketWorldReadableConstraintV1.iam-gcs-blacklist-public-users`

**Comment by briantkennedy** [comment]
Yeah, that was one side effect of the fact that someone could technically make a constraint named "test" for two different templates.  There wasn't a good way to handle that, so the thought was to put the template and constraint name together.
