### ISSUE TITLE
Update Config Validator to use opa v0.17.2

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/config-validator#122]
The policy-library repo was [recently updated](https://github.com/forseti-security/policy-library/pull/279) to use opa v0.17.2 (from v0.16.0). 

Config Validator will also need to be updated to use opa v0.17.2 to be synced, as it is [currently on v0.16.2](https://github.com/forseti-security/config-validator/blob/master/go.mod#L23).

**Comment by briantkennedy** [comment]
This is going to entail updating github.com/open-policy-agent/frameworks/constraint and github.com/open-policy-agent/gatekeeper to both use 0.17.2

Dependencies:
https://github.com/open-policy-agent/frameworks/issues/86
https://github.com/open-policy-agent/gatekeeper/issues/510

**Comment by hshin-g** [comment]
That sounds like a good idea- I've opened a PR here: https://github.com/forseti-security/policy-library/pull/284
