### ISSUE TITLE
Feature request: update Config Validator to support org policy & access levels

### ISSUE THREAD

**Issue by katze120** [forseti-security/config-validator#136]
Below asset_v1 protos have been updated to support org policy and access levels from Cloud Asset Inventory data

https://github.com/googleapis/googleapis/blob/master/google/cloud/asset/v1/assets.proto
https://github.com/googleapis/googleapis/blob/master/google/cloud/asset/v1/asset_service.proto

Can Config Validator be updated to pick up these changes too?

**Comment by morgante** [comment]
@briantkennedy were you looking at this?

**Comment by briantkennedy** [comment]
@morgante looking now, sorry, been dealing with a customer escalation

**Comment by briantkennedy** [comment]
@katze120 posted PR, please let me know if that's not exactly what you were looking for.
