### ISSUE TITLE
Expose Asset.AncestryPath in violations

### ISSUE THREAD

**Issue by katze120** [forseti-security/config-validator#140]
Let's expose Asset.[AncestryPath](https://github.com/forseti-security/config-validator/blob/master/pkg/api/validator/validator.pb.go#L46) in Violation.

Currently [Resource](https://github.com/forseti-security/config-validator/blob/master/api/validator.proto#L75) is a string field in Violation

**Comment by briantkennedy** [comment]
@katze120 what setup do you have for FCV?

**Comment by katze120** [comment]
> @katze120 what setup do you have for FCV?

not sure whether I understand what's being asked.. what does 'setup' mean in this context?

**Comment by briantkennedy** [comment]
Whoops, thought it might have been from using an old version, I mistook the fact that it had been added to insight to also think it was added to violation, posted PR to fix.
