### ISSUE TITLE
User Guide | cmd for policy-library to Forseti bucket

### ISSUE THREAD

**Issue by alexsgoogle** [forseti-security/config-validator#17]
Regarding this command: 
export POLICY_LIBRARY_PATH=path/to/local/policies/library

I think it would be clearer to finish the command as '/policy-library/'

And for the next command:
gsutil cp -r ${POLICY_LIBRARY_PATH} gs://${FORSETI_BUCKET}/policy-library/

do we actually mean this?
gsutil cp -r ${POLICY_LIBRARY_PATH} gs://${FORSETI_BUCKET}/
 
I accidentally created nested /policy-library/policy-library/

**Comment by t12g** [comment]
Done.
