### ISSUE TITLE
User Guide | running TF Validator first time

### ISSUE THREAD

**Issue by alexsgoogle** [forseti-security/config-validator#19]
Regarding this command:
./terraform-validator-linux-amd64 validate test.tfplan --policy-path=policy-library

At this point, I think we're supposed to have set the Project macro (or otherwise provide it as a flag), but I don't think we talk about this in the guide

**Comment by t12g** [comment]
The latest version of TF validator no longer requires it. It'll parse the project from the google provider block.
We mentioned that in the guide:
"Terraform Validator also accepts an optional --project flag which is set to the Terraform Google provider project. See the provider docs for more info. If it is not set, Terraform Validator will attempt to parse the provider project from the provider configuration."
