### ISSUE TITLE
Include resource type as part of the violation message

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/config-validator#27]
https://github.com/forseti-security/config-validator/blob/237d9245bc417f4afcaabd363f8367d5233f4f6e/api/validator.proto#L46

It's hard to determine whether or not a violation is a resource violation / iam violation since the resource name is identical in both cases but the data that's being scanned are different data.

**Comment by briantkennedy** [comment]
The full resource is now included in the metadata.
