### ISSUE TITLE
Support multiple documents in a single constraint .yaml file

### ISSUE THREAD

**Issue by t12g** [forseti-security/config-validator#29]
For a single constraint template, there can be multiple constraint .yaml files (10s? 100s?).  This can become unwieldy and get out of hand. 

YAML supports multiple documents in a single file (example in k8s testdata: https://github.com/kubernetes/kubernetes/blob/master/hack/testdata/multi-resource-yaml.yaml). 
Config Validator should support this too (at least for constraints).

**Comment by briantkennedy** [comment]
This is now handled.
