### ISSUE TITLE
Include metadata in violation message

### ISSUE THREAD

**Issue by sgalij** [forseti-security/config-validator#41]
Currently when constraint violation is detected tool returns message like this:

Found Violations:
[rego message]

It would be useful to include also policy **metadata** in this message.
Forseti Config Vaildator includes this data in violation report.

**Comment by morgante** [comment]
Are you using the Terraform validator?

How would you like the metadata surfaced?

**Comment by sgalij** [comment]
Rego rule schema according to OPA constraint framework is following:
```
deny[{"msg": msg, "details": {}}] {
  # rule body
}
```

So I suggest to add new flag --script and return only **details** json object when this flag is used.

BTW, I opened issue in wrong project.
Now I created another issue in:
https://github.com/GoogleCloudPlatform/terraform-validator/issues/35
