### ISSUE TITLE
Converge target and exclude semantics with Gatekeeper match semantics

### ISSUE THREAD

**Issue by morgante** [forseti-security/config-validator#42]
https://github.com/forseti-security/config-validator/pull/37#discussion_r287542782

**Comment by morgante** [comment]
Based on the conversation, we should move them to the top level:

```
match:
   target: ...
   exclude: ...
```

**Comment by t12g** [comment]
The config validator library now accepts both formats. TF validator has been updated. For Forseti, the upcoming 2.17 release should have this change as well. 

We can consider removing the support for old format in Forseti 2.18. @joecheuk WDYT?

**Comment by joecheuk** [comment]
Does removing supports meaning its gonna fail when consuming the old policies or its just gonna ignore the match field?
