### ISSUE TITLE
Config Validator not scaling to large datasets

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/config-validator#52]
In profiling large CAI exports with a dataset with 2M resources we are finding that the virtual machine is running out of memory.

Next Steps:
- [x] Prep for new RPC endpoint https://github.com/forseti-security/config-validator/pull/60
- [ ] Create new RPC endpoint in Config Validator (without referential support) 
  - [ ] Enable mult-threading of Config Validator auditing
- [ ] Forseti / Config Validator teams profile performance of new RPC end point with multi-threading

**Comment by dekuhn** [comment]
Assigning to @morgante who offered to do some initial investigations around memory the consumption with a large data set.

**Comment by morgante** [comment]
I did some preliminary analysis. The problem seems to be in OPA/Rego itself: https://docs.google.com/document/d/1AV23q8YqjSwaVv3FqXkzH7m7kInjyxWE3Xk2WH6xCWo/edit

**Comment by dekuhn** [comment]
@briantkennedy based on @morgante findings what is the right next step here regarding this issue?

**Comment by dekuhn** [comment]
@briantkennedy I wanted to document high level tasks related to this effort please review and edit.

- [ ] Prep for new RPC endpoint https://github.com/forseti-security/config-validator/pull/60
- [ ] Create new RPC endpoint in Config Validator (without referential support) 
  - [ ] Enable mult-threading of Config Validator auditing
- [ ] Forseti / Config Validator teams profile performance of new RPC end point with multi-threading

**Comment by briantkennedy** [comment]
yeah, that looks roughly like the path, although the PRs aren't necessarily going to map 1:1 there, we can edit as we go

**Comment by dekuhn** [comment]
@briantkennedy I will move the tasks to the first edit on this issue. We can update there as needed. Thanks.

**Comment by briantkennedy** [comment]
I believe this has been closed out.  Feel free to reopen if there's more work to do.

**Comment by morgante** [comment]
@katze120 Have we still been seeing issues with using CFT Scorecard against large CAI dumps?

**Comment by katze120** [comment]
I have some performance data here for running scorecard on macbook pro. I tried on CAI of 2G too, no out-of-memory issue but I terminated the process after 2+ hrs.

CAI file size | # of Projects | # of lines in CAI exports | Time to complete
-- | -- | -- | --
17M | 50 | 11567 | 4 mins
30M | 67 | 15508 | 6 mins
200M | 39047 | 247126 | 110 mins

Very often, large CAI size is caused by BQ tables. For now I'd recommend to exclude BQ tables from CAI file before running scorecard, unless there is any constraint for BQ table being used, which is rare.

**Comment by briantkennedy** [comment]
If there's a CAI dump and set of constraints you're able to give me, please reopen and I can take a last look at improving the single host performance, but other than that we are at the end of the road in terms of the single host performance story.
