### ISSUE TITLE
gcv.NewValidator should support multiple policy paths

### ISSUE THREAD

**Issue by yukinying** [forseti-security/config-validator#57]
This would give users a much better flexibilty to construct template and constraints into different directories. The current setting restricted the users to have them share the same parent. 

The code itself seems to be supporting that. First of all, NewValidator takes Options slices as input so it could possibly be extended to take multpile options and store the policy path as slice. Policy path is then passed to the loadYAMLFiles function which again could be easily modified to traverse all the provided path. It looks viable to patch the code to support that without modifying the external interfaces.

**Comment by briantkennedy** [comment]
This seems like it would be a pretty simple change, but it's going to have some conflicts with an existing workstream.  What's the priority on this change?

**Comment by yukinying** [comment]
I don't think this is blocking anything at this point, but this is a feature that would help people to bring multiple policies (e.g. centralized vs project specific) together without running the validation multiple times.
