### ISSUE TITLE
Support large Audit Responses

### ISSUE THREAD

**Issue by dragon1672** [forseti-security/config-validator#7]
@joecheuk with more context
The response is limited to 4mb by gRPC. We ran into issues of this limit being busted with a template that always returned a violation with large datasets.

Possible source for design: https://cloud.google.com/apis/design/design_patterns#list_pagination

**Comment by Red-Five** [comment]
Chunking large messages with gRPC: https://jbrandhorst.com/post/grpc-binary-blob-stream/

**Comment by dekuhn** [comment]
Can someone size how difficult this work is and eng effort to do it?

**Comment by t12g** [comment]
It's probably ~1 week's worth of work (including both server & client side).

**Comment by briantkennedy** [comment]
I believe this is fixed.
