### ISSUE TITLE
Panic on storage bucket

### ISSUE THREAD

**Issue by umairidris** [forseti-security/config-validator#75]
Hello,

I have a simple storage bucket being created which is causing a panic on the latest validator release.

To reproduce, create a main.tf with a storage bucket (don't deploy/create the bucket)
$ terraform plan -out plan.tfplan
$ terraform show -json plan.tfplan > input.json
$ ./terraform-validator-linux-amd64 validate input.json --policy-path=policy-library
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketApiObject(0x28699a0, 0xc000446e20, 0xc000568a00, 0x2456780, 0x21, 0xc0005b2580)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/storage_bucket.go:80 +0x1160
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketCaiObject(0x28699a0, 0xc000446e20, 0xc000568a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/storage_bucket.go:25 +0xdc
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).AddResource(0xc0003aa3c0, 0x2860560, 0xc0005a2340, 0xc0003aa420, 0xc0005a2300)
	/Users/morgantep/code/google/validator/terraform-validator/converters/google/convert.go:140 +0x14c
github.com/GoogleCloudPlatform/terraform-validator/tfgcv.ReadPlannedAssets(0x7ffd1fa75904, 0xa, 0x0, 0x0, 0x0, 0x0, 0x1cbd000, 0x0, 0x0, 0x0, ...)
	/Users/morgantep/code/google/validator/terraform-validator/tfgcv/planned_assets.go:93 +0x6b3
github.com/GoogleCloudPlatform/terraform-validator/cmd.glob..func6(0x3b0f520, 0xc000446c00, 0x1, 0x2, 0x0, 0x0)
	/Users/morgantep/code/google/validator/terraform-validator/cmd/validate.go:52 +0x9b
github.com/spf13/cobra.(*Command).execute(0x3b0f520, 0xc000446be0, 0x2, 0x2, 0x3b0f520, 0xc000446be0)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x3b0f2c0, 0x0, 0x0, 0x1ce2134)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/spf13/cobra/command.go:800
github.com/GoogleCloudPlatform/terraform-validator/cmd.Execute()
	/Users/morgantep/code/google/validator/terraform-validator/cmd/root.go:77 +0x2e
main.main()
	/Users/morgantep/code/google/validator/terraform-validator/main.go:20 +0x20

---

Debug info:
$ terraform version
Terraform v0.12.12
+ provider.google v2.18.1

Validator release: gs://terraform-validator/releases/2019-10-10/terraform-validator-linux-amd64

**Comment by morgante** [comment]
This should be fixed in the 2019-11-07 validator release.
