### ISSUE TITLE
NewValidator(stopChannel, ... ) could be refactored as NewValidator(ctx, ... )

### ISSUE THREAD

**Issue by yukinying** [forseti-security/config-validator#77]
This is a nit comment. It is more intuitive to use context and get the stopChannel via ctx.Done() which probably do the same thing. For anyone who are calling NewValidator, without a single thought, they can pass the ctx in without putting any concern on how this channel would be managed. Just a suggestion.

**Comment by briantkennedy** [comment]
If you'd like to create a PR, I'll review it.

**Comment by briantkennedy** [comment]
Validator no longer takes a stop channel, closing as obsolete.
