### ISSUE TITLE
Add documentation on gRPC errors

### ISSUE THREAD

**Issue by dragon1672** [forseti-security/config-validator#8]
The gRPCs are scattered in the codebase, some documentation could help make it easier for users of this library to keep track of what expect.

**Comment by dragon1672** [comment]
@t12g Do you have any recommendations?
I was thinking of making a directory readme.md, but I would be copying method names, which makes me want to provide more context on function comments.

**Comment by t12g** [comment]
I'd go with go doc function comments. But it's easy to lose track when there's a chain of invocation, unless we're being really diligent about this. This information can quickly become out of date.

**Comment by briantkennedy** [comment]
will not fix
