### ISSUE TITLE
Load constraints from GCS

### ISSUE THREAD

**Issue by kevensen** [forseti-security/config-validator#84]
As a user of config-validator, I would like to load the constraints from GCS in order to have config-validator be stateless.

**Comment by morgante** [comment]
What do you mean by config-validator being "stateless?" Whether constraints are read from GCS or from the filesystem doesn't affect whether its statefulness.

**Comment by kevensen** [comment]
Maybe stateless is the wrong adjective.  If I want to run this in Cloud Run, I'd have to pre-load the container image with the constraints in the image's file system.  This way, the contstraints don't have to be local to the config-validator process on startup.

**Comment by kevensen** [comment]
I'm happy to take this on btw.

**Comment by morgante** [comment]
Got it. Yes, I think reading constraints from GCS could have some value but I'm not necessarily sure that building it into Config Validator is necessary. Note that other solutions like FUSE could be used to mount GCS into a container: https://github.com/maciekrb/gcs-fuse-sample

**Comment by kevensen** [comment]
But isn't that faking an object store as a file store?

**Comment by morgante** [comment]
Yes it is, but for cases like this (low rw) it should work perfectly fine.

**Comment by kevensen** [comment]
Fair enough.  I think the challenge here is that we have do not have access to life-cycle hooks nor kernel capabilities with Cloud Run.

**Comment by morgante** [comment]
Fair enough. I'd certainly be happy to review a PR implementing this.

**Comment by kevensen** [comment]
Thank you sir.  Hopefully I can get that done in the next few days.

**Comment by briantkennedy** [comment]
What's the setup you have for cloudrun?  Why isn't building a docker container that contains thee specific constraints / templates acceptable?  I'd like to have more info before giving this sort of thing the green light.

**Comment by kevensen** [comment]
I do not have a setup yet.  If we were to add constraints and templates to a container image, we'd be rebuilding that container image every time a single file is updated.  To make this seamless, we could setup some CI/CD tooling in Cloud Build to trigger every time an update is made to policy-library.

In my mind, that is a lot of extra tooling to support the update of one file.

**Comment by briantkennedy** [comment]
So if I understand correctly, you're intending to add support for "gs://" URIs for policy directories and libraries?

**Comment by kevensen** [comment]
Exactly that!

**Comment by briantkennedy** [comment]
Oh, yeah, that's fine, the fuse suggestion threw me off there.
